### ISSUE TITLE
Do array of object schemas have to be formated in JSON?

### ISSUE THREAD

**Issue by Jared-Sprague** [phretaddin/schemapack#15] opened 2016-08-10 23:39 UTC
Hey @phretaddin!

I tried making a schema like this:

```
var playersSchema = sp.build([{
    health: "varuint",
    jumping: "boolean",
    position: [ "int16" ],
    attributes: { str: 'uint8', agi: 'uint8', int: 'uint8' }
}]);

    var players = [
    {
        health: 4000,
        jumping: true,
        position: [ -540, 343, 1201 ],
        attributes: { str: 87, agi: 42, int: 22 }
    },
    {
        health: 5000,
        jumping: false,
        position: [ -540, 343, 1201 ],
        attributes: { str: 87, agi: 42, int: 22 }
    }
];

var buffer = playersSchema.encode(players);
```

But was getting this error on the client:
![screenshot from 2016-08-10 19-37-18](https://cloud.githubusercontent.com/assets/3926730/17574778/e9e54126-5f31-11e6-8421-5f2a6cad2e6e.png)

Then I noticed in person-array.js test this:
```
[ { "name": "string", "numbers": [ "varint" ], "age": "uint8" } ]
```

And that works, So it looks like if you want to have an array of objects schema, the object in the array schema has to be written in JSON?

Thanks!

**Comment by phretaddin** [comment] 2016-08-11 00:40
Thanks for bringing this to my attention. I think I see what the problem is. Give me a bit to roll out a patch.

**Comment by phretaddin** [comment] 2016-08-11 02:20
Ok, I committed a change. Let me know if this works for you.

**Comment by Jared-Sprague** [comment] 2016-08-11 03:21
Thanks a lot! That seems to have done the trick!

**Closed** 2016-08-11 03:26 UTC
