### ISSUE TITLE
NodeJS 6.4.0 Empty String Range Error

### ISSUE THREAD

**Issue by Buffele** [phretaddin/schemapack#18] opened 2016-08-16 17:31 UTC
Hello,

Only affects latest NodeJS (6.4.0) Version. 6.3.1 worked fine.

``` javascript
var sp = require('../schemapack')

var stringSchema = sp.build('string')

var data = stringSchema.encode('')
var decoded = stringSchema.decode(data)

console.log(decoded)
```

Output:

`````` buffer.js:761
        return this.utf8Write(string, offset, length);
                    ^

RangeError: Offset is out of bounds
    at RangeError (native)
    at Buffer.write (buffer.js:761:21)
    at Object.writeString (D:\Projects\schemapack\schemapack.js:67:29)
    at eval (eval at getCompiledSchema (D:\Projects\schemapack\schemapack.js:374:24), <anonymous>:3:209)
    at Object.encode (D:\Projects\schemapack\schemapack.js:389:14)
    at Object.<anonymous> (D:\Projects\schempack_test\test.js:5:25)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)```
``````

**Comment by phretaddin** [comment] 2016-08-16 19:34
Hello! Looks like there was a change in the `utf8Write` implementation in Node between versions 6.3.1 and 6.4. I'll make an issue on their Github to see if it's intentional. If so, I'll just patch schemapack to check for strings of length 0 before writing.

**Comment by phretaddin** [comment] 2016-08-18 13:29
The Node.js team confirmed this as a bug. Looks like it will be fixed in their next release. Just use 6.3.1 in the meantime, I suppose.

**Closed as completed by phretaddin** 2016-08-18 13:29 UTC

**Comment by noahwalugembe** [comment] 2017-08-28 07:16
Can some one send me a client side implementation of schemapack.
